version: '3.3'

services:
  app:
    build: .
    image: ${IMAGE_NAME}:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4 # Use a specific version for stability
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:

