apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: aws-key64
  AWS_SECRET_ACCESS_KEY: aws-secret64
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME:  username64
  MONGO_INITDB_ROOT_PASSWORD:  password64
  

