apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws_access_key_id: #base64 aws accesskey
  aws_secret_access_key: #base64 aws secretkey
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username:  # base64 for 'username'
  mongo-root-password:  # base64 for 'password'

